// @ts-nocheck -- generated by scripts/build-edge.mjs
// src/server/geminiService.ts
import { GoogleGenAI } from "npm:@google/genai@2.4.0";

// src/models.ts
var AI_MODELS = [
  {
    id: "gemini-3.8-flash",
    name: "Gemini 3.8 Flash",
    tag: "Penalaran mendalam",
    description: "Untuk latihan analitis dan materi yang kompleks."
  },
  {
    id: "gemini-3.7-flash",
    name: "Gemini 3.7 Flash",
    tag: "Penalaran & analisis",
    description: "Untuk latihan dengan penalaran bertahap dan analisis konsep."
  },
  {
    id: "gemini-3.6-flash",
    name: "Gemini 3.6 Flash",
    tag: "Serbaguna",
    description: "Untuk pemahaman terapan dan beragam topik belajar."
  },
  {
    id: "gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    tag: "Latihan harian",
    description: "Untuk membangun pemahaman melalui latihan rutin."
  },
  {
    id: "gemini-3.5-flash-lite",
    name: "Gemini 3.5 Flash Lite",
    tag: "Cepat & efisien",
    description: "Untuk latihan harian dengan respons yang ringan."
  },
  {
    id: "gemma-4-31b-it",
    name: "Gemma 4 31B",
    tag: "Model terbuka \xB7 31B",
    description: "Alternatif model Gemma untuk eksplorasi dan latihan konsep."
  }
];
var DEFAULT_MODEL = "gemini-3.8-flash";
var isAIModel = (value) => AI_MODELS.some((model) => model.id === value);
var DIFFICULTIES = [
  {
    id: "primitive",
    name: "Primitif",
    description: "Mengenali fakta paling dasar, dengan pertanyaan langsung dan opsi sederhana."
  },
  {
    id: "very_easy",
    name: "Sangat mudah",
    description: "Mengingat istilah dan konsep dasar dengan konteks yang familiar."
  },
  {
    id: "easy",
    name: "Mudah",
    description: "Memahami konsep dasar dan hubungan sederhana antaride."
  },
  {
    id: "moderate",
    name: "Sedang",
    description: "Menerapkan satu konsep pada contoh atau situasi sehari-hari."
  },
  {
    id: "intermediate",
    name: "Menengah",
    description: "Menghubungkan beberapa konsep dan melakukan analisis terapan."
  },
  {
    id: "hard",
    name: "Sulit",
    description: "Menganalisis studi kasus dan menyelesaikan masalah bertahap."
  },
  {
    id: "very_hard",
    name: "Sangat sulit",
    description: "Mengevaluasi masalah kompleks dengan beberapa sudut pandang."
  },
  {
    id: "master",
    name: "Master",
    description: "Mensintesis konsep tingkat pakar dengan penalaran abstrak mendalam."
  },
  {
    id: "grand_master",
    name: "Grand master",
    description: "Memecahkan persoalan orisinal tingkat kompetisi dengan sintesis lintas konsep."
  }
];

// src/quizConfig.ts
var QuizConfigError = class extends Error {
};
function normalizeQuizConfig(input) {
  if (!input || typeof input !== "object" || Array.isArray(input))
    throw new QuizConfigError("Konfigurasi kuis tidak valid.");
  const body = input;
  if (typeof body.topic !== "string" || !body.topic.trim())
    throw new QuizConfigError("Topik kuis tidak boleh kosong.");
  const model = body.model ?? DEFAULT_MODEL;
  if (!isAIModel(model)) throw new QuizConfigError("Model AI tidak didukung.");
  const difficulty = { beginner: "easy", advanced: "hard", expert: "master" }[String(body.difficulty)] ?? body.difficulty ?? "intermediate";
  if (!DIFFICULTIES.some((level) => level.id === difficulty))
    throw new QuizConfigError("Tingkat kesulitan tidak didukung.");
  const count = Number(body.questionCount ?? 5);
  if (!Number.isInteger(count) || count < 1 || count > 100)
    throw new QuizConfigError(
      "Jumlah soal harus bilangan bulat antara 1 dan 100."
    );
  const displayMode = body.displayMode ?? "non_sequential";
  if (displayMode !== "non_sequential" && displayMode !== "sequential")
    throw new QuizConfigError("Tampilan soal tidak didukung.");
  const minutes = Number(body.timeLimitMinutes ?? 10);
  if (!Number.isFinite(minutes) || minutes < 0 || minutes > 120)
    throw new QuizConfigError("Durasi total harus antara 0 dan 120 menit.");
  const seconds = Number(
    body.timePerQuestionSeconds ?? (minutes === 0 ? 0 : 60)
  );
  if (!Number.isInteger(seconds) || seconds < 0 || seconds > 600)
    throw new QuizConfigError("Durasi per soal harus antara 0 dan 600 detik.");
  const optionalText = (value, max) => typeof value === "string" ? value.trim().slice(0, max) || void 0 : void 0;
  return {
    model,
    topic: body.topic.trim().slice(0, 300),
    studyMaterial: optionalText(body.studyMaterial, 15e3),
    difficulty,
    questionCount: count,
    displayMode,
    timeLimitMinutes: minutes,
    timePerQuestionSeconds: displayMode === "sequential" ? seconds : void 0,
    language: body.language === "en" ? "en" : "id",
    enableGrounding: body.enableGrounding !== false,
    languageStyle: optionalText(body.languageStyle, 500),
    additionalInstructions: optionalText(body.additionalInstructions, 2e3)
  };
}
function quizTimerSeconds(quiz) {
  return quiz.displayMode === "sequential" ? quiz.timePerQuestionSeconds ?? (quiz.timeLimitMinutes === 0 ? 0 : 60) : quiz.timeLimitMinutes * 60;
}
function durationLabel(seconds) {
  if (seconds === 0) return "Tanpa batas";
  const minutes = Math.floor(seconds / 60);
  const remainder = seconds % 60;
  return [
    minutes ? `${minutes} menit` : "",
    remainder ? `${remainder} detik` : ""
  ].filter(Boolean).join(" ");
}

// src/server/jsonParser.ts
function sanitizeAndParseJson(raw) {
  if (!raw || typeof raw !== "string") {
    throw new Error("Respon kosong atau bukan string.");
  }
  let text = raw.trim();
  const codeBlock = text.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
  if (codeBlock && codeBlock[1]) {
    text = codeBlock[1].trim();
  }
  const firstBrace = text.indexOf("{");
  const lastBrace = text.lastIndexOf("}");
  if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
    text = text.substring(firstBrace, lastBrace + 1);
  }
  try {
    return JSON.parse(text);
  } catch {
  }
  let sanitized = text.replace(/\\([a-zA-Z])/g, (_, ch) => "\\\\" + ch);
  sanitized = sanitized.replace(/,\s*([}\]])/g, "$1");
  try {
    return JSON.parse(sanitized);
  } catch {
  }
  sanitized = sanitized.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, " ");
  try {
    return JSON.parse(sanitized);
  } catch {
  }
  let openBraces = 0;
  let openBrackets = 0;
  let inString = false;
  let escaped = false;
  for (let i = 0; i < sanitized.length; i++) {
    const char = sanitized[i];
    if (char === '"' && !escaped) inString = !inString;
    if (!inString) {
      if (char === "{") openBraces++;
      else if (char === "}") openBraces = Math.max(0, openBraces - 1);
      else if (char === "[") openBrackets++;
      else if (char === "]") openBrackets = Math.max(0, openBrackets - 1);
    }
    escaped = char === "\\" && !escaped;
  }
  if (inString) sanitized += '"';
  while (openBrackets > 0) {
    sanitized += "]";
    openBrackets--;
  }
  while (openBraces > 0) {
    sanitized += "}";
    openBraces--;
  }
  sanitized = sanitized.replace(/,\s*([}\]])/g, "$1");
  try {
    return JSON.parse(sanitized);
  } catch (err) {
    throw new Error("Gagal mengekstrak struktur kuis JSON dari respon model AI: " + err.message);
  }
}

// src/server/geminiService.ts
var QuizGenerationError = class extends Error {
  constructor(message, status = 500, code = "GENERATION_ERROR") {
    super(message);
    this.status = status;
    this.code = code;
    this.name = "QuizGenerationError";
  }
};
function getGeminiClient(apiKey = process.env.GEMINI_API_KEY) {
  if (!apiKey || apiKey === "MY_GEMINI_API_KEY") {
    throw new QuizGenerationError(
      "GEMINI_API_KEY belum dikonfigurasi di lingkungan runtime.",
      401,
      "API_KEY_MISSING"
    );
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      timeout: 18e4
      // 3 menit untuk penalaran mendalam Gemma & batching
    }
  });
}
async function generateQuizBatch(input, apiKey, existing = [], signal) {
  const config = normalizeQuizConfig(input);
  const ai = new GoogleGenAI({ apiKey, httpOptions: { timeout: 75e3 } });
  const model = config.model ?? DEFAULT_MODEL;
  const gemma = model === "gemma-4-31b-it";
  const prompt = buildPrompt(config, config.questionCount, existing);
  try {
    const response = await ai.models.generateContent({
      model,
      contents: gemma ? buildGemmaPrompt(config, config.questionCount, existing) : prompt.userPrompt,
      config: {
        abortSignal: signal,
        ...gemma ? {} : { systemInstruction: prompt.systemInstruction },
        ...!gemma && config.enableGrounding ? { tools: [{ googleSearch: {} }] } : {}
      }
    });
    const parsed = extractJsonFromResponse(response.text || "");
    const sources = (response.candidates?.[0]?.groundingMetadata?.groundingChunks || []).filter((chunk) => chunk.web?.uri).map((chunk) => ({ title: chunk.web.title || "Referensi", url: chunk.web.uri }));
    const previous = new Set(existing.map((q) => q.trim().toLowerCase()));
    const questions = [];
    for (const raw of Array.isArray(parsed.questions) ? parsed.questions : []) {
      const question = validateAndSanitizeQuestion(raw, questions.length, config.topic, sources);
      if (question && !previous.has(question.question.trim().toLowerCase())) {
        question.id = crypto.randomUUID();
        questions.push(question);
        previous.add(question.question.trim().toLowerCase());
      }
    }
    if (questions.length !== config.questionCount) throw new QuizGenerationError("Jumlah soal valid belum sesuai. Batch dihentikan untuk mencegah hasil tidak lengkap.", 502, "INCOMPLETE_QUESTION_COUNT");
    return {
      id: crypto.randomUUID(),
      title: String(parsed.title || `Kuis: ${config.topic}`),
      summary: String(parsed.summary || ""),
      ...config,
      createdAt: (/* @__PURE__ */ new Date()).toISOString(),
      questions,
      requestedModel: model,
      model,
      usedGrounding: !gemma && config.enableGrounding,
      groundingQueriesUsed: response.candidates?.[0]?.groundingMetadata?.webSearchQueries || []
    };
  } catch (error) {
    if (signal?.aborted) throw new DOMException("Operasi dibatalkan", "AbortError");
    throw classifyApiError(error, model);
  }
}
function classifyApiError(err, modelId) {
  if (err instanceof QuizGenerationError) {
    return err;
  }
  const msg = String(err?.message || err);
  const isGemma = modelId === "gemma-4-31b-it";
  const modelLabel = isGemma ? "Gemma 4 31B" : "Gemini";
  if (/401|API_KEY_INVALID|API key not valid|UNAUTHENTICATED/i.test(msg)) {
    return new QuizGenerationError(
      `API key tidak diterima atau tidak valid untuk ${modelLabel}. Periksa API key Anda di Google AI Studio.`,
      401,
      "UNAUTHORIZED"
    );
  }
  if (/403|PERMISSION_DENIED/i.test(msg)) {
    return new QuizGenerationError(
      `Akses ke model ${modelLabel} ditolak (403 Forbidden). Pastikan API key Anda memiliki izin akses untuk model ini di Google AI Studio.`,
      403,
      "FORBIDDEN"
    );
  }
  if (/404|NOT_FOUND|is not found|is no longer available/i.test(msg)) {
    return new QuizGenerationError(
      `Model ${modelLabel} (${modelId}) tidak ditemukan atau tidak tersedia untuk akun/wilayah proyek Anda (404 Not Found).`,
      404,
      "MODEL_NOT_FOUND"
    );
  }
  if (/429|RESOURCE_EXHAUSTED|quota|rate limit/i.test(msg)) {
    return new QuizGenerationError(
      `Batas kuota atau rate limit untuk model ${modelLabel} telah tercapai (429 Too Many Requests). Tunggu sejenak sebelum mencoba lagi.`,
      429,
      "RATE_LIMIT_EXCEEDED"
    );
  }
  if (/503|UNAVAILABLE|high demand|overloaded/i.test(msg)) {
    return new QuizGenerationError(
      `Layanan ${modelLabel} sedang mengalami lonjakan permintaan (503 Service Unavailable). Silakan klik "Coba Lagi" dalam beberapa detik.`,
      503,
      "HIGH_DEMAND"
    );
  }
  if (/504|DEADLINE_EXCEEDED|timeout|ETIMEDOUT|UND_ERR_HEADERS_TIMEOUT/i.test(msg)) {
    return new QuizGenerationError(
      `Permintaan pembuatan kuis dengan ${modelLabel} melebihi batas waktu eksekusi (504 Gateway Timeout). Silakan coba lagi.`,
      504,
      "TIMEOUT"
    );
  }
  if (/500|INTERNAL/i.test(msg)) {
    return new QuizGenerationError(
      `Terjadi kesalahan internal pada server Google AI saat memproses permintaan ${modelLabel} (500 Internal Server Error). Silakan coba lagi.`,
      500,
      "PROVIDER_INTERNAL_ERROR"
    );
  }
  if (/fetch failed|ECONNRESET|ENOTFOUND|network/i.test(msg)) {
    return new QuizGenerationError(
      `Gagal terhubung ke server Google AI saat memanggil ${modelLabel}. Periksa koneksi internet Anda.`,
      504,
      "NETWORK_ERROR"
    );
  }
  return new QuizGenerationError(
    `Gagal membuat kuis dengan ${modelLabel}: ${msg}`,
    502,
    "GENERATION_FAILED"
  );
}
async function withTimeout(promise, timeoutMs = 9e4, label = "Permintaan AI") {
  let timer;
  const timeoutPromise = new Promise((_, reject) => {
    timer = setTimeout(() => {
      reject(new QuizGenerationError(`${label} melebihi batas waktu maksimal (${timeoutMs / 1e3} detik).`, 504, "TIMEOUT"));
    }, timeoutMs);
  });
  try {
    return await Promise.race([promise, timeoutPromise]);
  } finally {
    if (timer) clearTimeout(timer);
  }
}
async function callWithRetry(fn, maxRetries = 2, baseDelayMs = 2e3, modelId = "", timeoutMs = modelId === "gemma-4-31b-it" ? 15e4 : 9e4) {
  let lastErr;
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      return await withTimeout(fn(), timeoutMs, `Permintaan model ${modelId}`);
    } catch (err) {
      lastErr = err;
      const msg = String(err?.message || err);
      const isPermanent = /400|401|403|404|429|API_KEY_INVALID|PERMISSION_DENIED|NOT_FOUND|RESOURCE_EXHAUSTED|quota/i.test(msg);
      if (isPermanent) {
        throw classifyApiError(err, modelId);
      }
      const isTransient = /500|502|503|504|INTERNAL|UNAVAILABLE|DEADLINE_EXCEEDED|fetch failed|ECONNRESET|ETIMEDOUT|Headers Timeout/i.test(
        msg
      );
      if (attempt < maxRetries && isTransient) {
        const jitter = Math.random() * 500;
        const delay = baseDelayMs * Math.pow(2, attempt) + jitter;
        await new Promise((r) => setTimeout(r, delay));
        continue;
      }
      throw classifyApiError(err, modelId);
    }
  }
  throw classifyApiError(lastErr, modelId);
}
function validateAndSanitizeQuestion(q, idx, topic, extractedSources) {
  if (!q || typeof q !== "object") return null;
  const questionText = typeof q.question === "string" ? q.question.trim() : "";
  if (!questionText || questionText.length < 5) return null;
  let rawOptions = [];
  if (Array.isArray(q.options)) {
    rawOptions = q.options.map((o) => String(o ?? "").trim()).filter(Boolean);
  }
  if (rawOptions.length < 4) return null;
  const options = rawOptions.slice(0, 4);
  let correctIndex = Number(q.correctAnswerIndex);
  if (!Number.isInteger(correctIndex) || correctIndex < 0 || correctIndex > 3) {
    return null;
  }
  const explanation = typeof q.explanation === "string" && q.explanation.trim().length > 0 ? q.explanation.trim() : "Penalaran akademis mendalam terhadap konsep butir soal.";
  const questionSources = [...extractedSources];
  if (Array.isArray(q.groundingReferences)) {
    for (const ref of q.groundingReferences) {
      if (ref?.url && typeof ref.url === "string" && /^https?:\/\//i.test(ref.url)) {
        questionSources.push({
          title: String(ref.title || "Referensi Akademis"),
          url: ref.url,
          snippet: String(ref.title || ref.url)
        });
      }
    }
  }
  if (q.referenceTitle && typeof q.referenceTitle === "string" && q.referenceTitle.trim().length > 0) {
    questionSources.push({
      title: q.referenceTitle.trim(),
      url: "",
      snippet: `Rujukan ilmiah: ${q.referenceTitle.trim()}`
    });
  }
  return {
    id: `q_${idx + 1}_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
    question: questionText,
    options,
    correctAnswerIndex: correctIndex,
    explanation,
    groundingSources: questionSources.slice(0, 3),
    topicCategory: q.topicCategory ? String(q.topicCategory).trim() : topic
  };
}
function buildPrompt(config, targetCount, existingQuestions = []) {
  const isEn = config.language === "en";
  const level = DIFFICULTIES.find((item) => item.id === config.difficulty);
  const difficultyDesc = `${level.name}: ${level.description}`;
  const langPrompt = isEn ? "All questions, options, explanations, and summaries MUST be written in fluent, academic English." : "Semua pertanyaan, pilihan jawaban, penjelasan, dan ringkasan WAJIB ditulis dalam Bahasa Indonesia yang baik, lugas, dan akurat.";
  const systemInstruction = `Anda adalah Academic Assessment Engine tingkat tinggi.
Tugas Anda:
1. Menghasilkan butir soal kuis pilihan ganda yang bermutu tinggi, berbobot, presisi, dan terverifikasi secara ilmiah.
2. Setiap butir soal WAJIB memiliki tepat 4 opsi pilihan (A, B, C, D) yang jelas, masuk akal, dan tidak ambigu, dengan 1 kunci jawaban benar dan 3 distractor (pengecoh) realistis.
3. Hindari pertanyaan ambigu atau pilihan ganda dengan jawaban ganda.
4. Terapkan penalaran mendalam pada bagian pembahasan (explanation): jelaskan konsep mengapa kunci jawaban benar dan mengapa opsi pengecoh keliru.
5. ${langPrompt}
6. JANGAN membuat URL tautan internet fiktif atau palsu. Jika ada rujukan akademis nyata (buku teks/jurnal), sebutkan judul/nama rujukan pada "referenceTitle". Jika tidak ada, kosongkan string "".
7. Output WAJIB berupa blok JSON murni yang valid tanpa teks pembuka atau penutup di luar blok JSON.`;
  let userPrompt = `Buatkan kuis pilihan ganda dengan spesifikasi berikut:
- Topik Utama: "${config.topic}"
- Tingkat Kesulitan: ${difficultyDesc}
- Jumlah Soal: ${targetCount} butir soal
- Tampilan: ${config.displayMode === "sequential" ? "Satu soal per langkah" : "Semua soal dengan navigasi bebas"}
- Durasi: ${durationLabel(quizTimerSeconds(config))}${quizTimerSeconds(config) > 0 ? config.displayMode === "sequential" ? " per soal" : " total kuis" : ""}
- Gaya bahasa: ${config.languageStyle || "Jelas, baku, dan akademis"}
`;
  if (existingQuestions.length > 0) {
    userPrompt += `
PENTING: Butir-butir soal berikut sudah dibuat sebelumnya, JANGAN membuat soal yang serupa atau berulang:
${existingQuestions.map((q, i) => `${i + 1}. ${q}`).join("\n")}
`;
  }
  if (config.additionalInstructions) {
    userPrompt += `
Preferensi tambahan pengguna (ikuti selama tetap sesuai topik, bahasa, tingkat kesulitan, jumlah soal, akurasi, dan format JSON di atas):
${config.additionalInstructions}
`;
  }
  if (config.studyMaterial && config.studyMaterial.trim().length > 0) {
    userPrompt += `
Referensi Catatan / Materi Bahan Bacaan Khusus:
"""
${config.studyMaterial.trim().slice(0, 15e3)}
"""
Gali butir-butir soal utama berdasarkan materi referensi di atas dengan ketat!
`;
  }
  userPrompt += `
Format respon JSON yang WAJIB dihasilkan:
\`\`\`json
{
  "title": "${isEn ? "Academic Quiz Title" : "Judul Kuis yang Menarik dan Akademis"}",
  "topic": "${config.topic}",
  "summary": "${isEn ? "Brief 1-2 sentence focus summary." : "Ringkasan 1-2 kalimat mengenai fokus materi kuis ini."}",
  "questions": [
    {
      "question": "Kalimat pertanyaan yang jelas, lugas, dan terstruktur?",
      "options": [
        "Pilihan A",
        "Pilihan B",
        "Pilihan C",
        "Pilihan D"
      ],
      "correctAnswerIndex": 0,
      "explanation": "Penalaran mendalam: Mengapa opsi ini benar secara faktual, dan mengapa opsi lainnya keliru atau kurang tepat.",
      "topicCategory": "Sub-kategori topik soal",
      "referenceTitle": ""
    }
  ]
}
\`\`\`
Pastikan index "correctAnswerIndex" adalah angka 0, 1, 2, atau 3. Variasikan posisi kunci jawaban agar seimbang.
Hasilkan tepat ${targetCount} butir soal sekarang.
`;
  return { systemInstruction, userPrompt };
}
function buildGemmaPrompt(config, targetCount, existingQuestions = []) {
  const isEn = config.language === "en";
  const level = DIFFICULTIES.find((item) => item.id === config.difficulty);
  const difficultyDesc = `${level.name}: ${level.description}`;
  const langInstruction = isEn ? "All questions, options, explanations, and summaries MUST be written in fluent, academic English." : "All questions, options, explanations, and summaries MUST be written in fluent, grammatically correct Indonesian (Bahasa Indonesia).";
  let prompt = `You are an Academic Assessment Engine.
Create ${targetCount} high-quality multiple choice quiz question(s) about the topic: "${config.topic}".
Language requirement: ${langInstruction}
Difficulty level: ${difficultyDesc}.
Language style: ${config.languageStyle || "Clear, academic, and structured"}.

Requirements:
1. Provide exactly 4 distinct options per question.
2. Provide a single correct answer with "correctAnswerIndex" (0, 1, 2, or 3). Vary the position of the correct answer.
3. Provide a thorough scientific/conceptual explanation for "explanation", explaining why the correct option is right and others are incorrect.
4. Do NOT generate fake internet links or URLs. If there is a real published academic textbook or paper, provide its title in "referenceTitle", otherwise leave it as "".
`;
  if (existingQuestions.length > 0) {
    prompt += `
CRITICAL: Do NOT generate questions similar or redundant to these previously generated questions:
${existingQuestions.map((q, i) => `${i + 1}. ${q}`).join("\n")}
`;
  }
  if (config.additionalInstructions) {
    prompt += `
Additional user preferences (follow these while respecting topic, language, and JSON schema):
${config.additionalInstructions}
`;
  }
  if (config.studyMaterial && config.studyMaterial.trim().length > 0) {
    prompt += `
Study Material Reference:
"""
${config.studyMaterial.trim().slice(0, 1e4)}
"""
Base the assessment questions strictly on the study material provided above.
`;
  }
  prompt += `
Respond strictly with valid JSON conforming to this schema:
{
  "title": "${isEn ? "Academic Quiz: " + config.topic : "Kuis: " + config.topic}",
  "topic": "${config.topic}",
  "summary": "${isEn ? "Brief concept summary of this quiz." : "Ringkasan singkat konsep materi kuis ini."}",
  "questions": [
    {
      "question": "${isEn ? "Clear question sentence?" : "Kalimat pertanyaan yang jelas dan terstruktur dalam bahasa Indonesia?"}",
      "options": [
        "Option A",
        "Option B",
        "Option C",
        "Option D"
      ],
      "correctAnswerIndex": 0,
      "explanation": "${isEn ? "Detailed explanation of why this answer is correct." : "Penjelasan detail konsep mengapa opsi ini benar."}",
      "topicCategory": "${config.topic}",
      "referenceTitle": ""
    }
  ]
}
Return only valid JSON without any markdown formatting or commentary outside the JSON block. Generate exactly ${targetCount} question(s) now.`;
  return prompt;
}
async function generateQuizWithGemini(config, apiKey) {
  config = normalizeQuizConfig(config);
  const selectedModel = config.model ?? DEFAULT_MODEL;
  const isGemma = selectedModel === "gemma-4-31b-it";
  const ai = getGeminiClient(apiKey);
  const modelCandidates = isGemma ? [selectedModel] : [selectedModel, selectedModel === DEFAULT_MODEL ? "gemini-3.5-flash-lite" : DEFAULT_MODEL, "gemini-flash-latest"];
  const quizId = "quiz_" + Date.now() + "_" + Math.random().toString(36).substring(2, 7);
  let quizTitle = `Kuis: ${config.topic}`;
  let quizSummary = `Kuis evaluasi topik ${config.topic} tingkat ${config.difficulty}.`;
  let usedModelName = selectedModel;
  let usedGrounding = false;
  let allGroundingQueries = [];
  const validQuestions = [];
  const batchSize = isGemma ? config.questionCount > 2 ? 2 : config.questionCount : config.questionCount;
  const totalNeeded = config.questionCount;
  while (validQuestions.length < totalNeeded) {
    const remainingCount = totalNeeded - validQuestions.length;
    const currentBatchCount = Math.min(batchSize, remainingCount);
    let rawResponse = null;
    let lastError = null;
    const extractedSources = [];
    if (config.enableGrounding && !isGemma && validQuestions.length === 0) {
      const { systemInstruction, userPrompt } = buildPrompt(
        config,
        currentBatchCount,
        validQuestions.map((q) => q.question)
      );
      try {
        rawResponse = await callWithRetry(
          () => ai.models.generateContent({
            model: selectedModel,
            contents: userPrompt,
            config: {
              systemInstruction,
              tools: [{ googleSearch: {} }]
            }
          }),
          0,
          2e3,
          selectedModel
        );
        usedGrounding = true;
        usedModelName = selectedModel;
      } catch (err) {
        lastError = err;
      }
    }
    if (!rawResponse) {
      if (isGemma) {
        const gemmaPrompt = buildGemmaPrompt(
          config,
          currentBatchCount,
          validQuestions.map((q) => q.question)
        );
        try {
          rawResponse = await callWithRetry(
            () => ai.models.generateContent({
              model: selectedModel,
              contents: gemmaPrompt
            }),
            2,
            2e3,
            selectedModel
          );
          usedModelName = selectedModel;
          lastError = null;
        } catch (err) {
          lastError = err;
        }
      } else {
        const { systemInstruction, userPrompt } = buildPrompt(
          config,
          currentBatchCount,
          validQuestions.map((q) => q.question)
        );
        for (const model of modelCandidates) {
          try {
            rawResponse = await callWithRetry(
              () => ai.models.generateContent({
                model,
                contents: userPrompt,
                config: { systemInstruction }
              }),
              0,
              1500,
              model
            );
            usedModelName = model;
            lastError = null;
            break;
          } catch (err) {
            lastError = err;
          }
        }
      }
    }
    if (!rawResponse || !rawResponse.text) {
      throw classifyApiError(lastError || new Error("Respons model AI kosong."), usedModelName);
    }
    const rawText = rawResponse.text || "";
    const candidate = rawResponse.candidates?.[0];
    const groundingMetadata = candidate?.groundingMetadata;
    if (groundingMetadata?.webSearchQueries) {
      allGroundingQueries.push(...groundingMetadata.webSearchQueries);
    }
    if (groundingMetadata?.groundingChunks) {
      for (const chunk of groundingMetadata.groundingChunks) {
        if (chunk.web?.uri) {
          extractedSources.push({
            title: chunk.web.title || "Sumber Google Search",
            url: chunk.web.uri,
            snippet: chunk.web.title || chunk.web.uri
          });
        }
      }
    }
    const parsedData = extractJsonFromResponse(rawText);
    if (parsedData.title && typeof parsedData.title === "string") {
      quizTitle = parsedData.title;
    }
    if (parsedData.summary && typeof parsedData.summary === "string") {
      quizSummary = parsedData.summary;
    }
    const rawQuestions = Array.isArray(parsedData.questions) ? parsedData.questions : [];
    let addedInThisBatch = 0;
    for (const rawQ of rawQuestions) {
      if (validQuestions.length >= totalNeeded) break;
      const validated = validateAndSanitizeQuestion(
        rawQ,
        validQuestions.length,
        config.topic,
        extractedSources
      );
      if (validated) {
        const isDuplicate = validQuestions.some(
          (existing) => existing.question.toLowerCase().trim() === validated.question.toLowerCase().trim()
        );
        if (!isDuplicate) {
          validQuestions.push(validated);
          addedInThisBatch++;
        }
      }
    }
    if (addedInThisBatch === 0 && validQuestions.length < totalNeeded) {
      break;
    }
  }
  if (validQuestions.length < totalNeeded) {
    if (validQuestions.length === 0) {
      throw new QuizGenerationError(
        `Model ${isGemma ? "Gemma 4 31B" : "AI"} tidak menghasilkan butir soal dengan struktur valid. Silakan coba kembali.`,
        502,
        "INVALID_QUIZ_STRUCTURE"
      );
    }
    throw new QuizGenerationError(
      `Model menghasilkan ${validQuestions.length} soal valid dari ${totalNeeded} yang diminta. Silakan buat kuis kembali.`,
      502,
      "INCOMPLETE_QUESTION_COUNT"
    );
  }
  const resultQuiz = {
    id: quizId,
    title: quizTitle,
    topic: config.topic,
    summary: quizSummary,
    difficulty: config.difficulty,
    timeLimitMinutes: config.timeLimitMinutes,
    displayMode: config.displayMode,
    timePerQuestionSeconds: config.timePerQuestionSeconds,
    languageStyle: config.languageStyle,
    additionalInstructions: config.additionalInstructions,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    questions: validQuestions.slice(0, totalNeeded),
    groundingQueriesUsed: allGroundingQueries,
    requestedModel: selectedModel,
    model: usedModelName,
    usedGrounding
  };
  return resultQuiz;
}
function extractJsonFromResponse(text) {
  try {
    return sanitizeAndParseJson(text);
  } catch (err) {
    throw new QuizGenerationError(
      "Gagal mengekstrak struktur kuis JSON dari respon model AI: " + (err?.message || String(err)),
      502,
      "INVALID_JSON"
    );
  }
}
export {
  QuizGenerationError,
  classifyApiError,
  extractJsonFromResponse,
  generateQuizBatch,
  generateQuizWithGemini
};
