import React,{useEffect,useState} from 'react';
import type { EvaluationSettings,Quiz,QuizSubmission } from '../types/quiz.js';
import { normalizeEvaluationSettings,saveEvaluationPreferences } from '../evaluationSettings.js';
import { AI_MODELS,defaultProviderModel,type AIProvider } from '../models.js';
import { fetchApi,safeError } from '../api.js';
export function AIEvaluationSettings({value,onSave}:{value:EvaluationSettings;onSave:(s:EvaluationSettings)=>Promise<void>}){
 const [draft,setDraft]=useState(value),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>setDraft(value),[JSON.stringify(value)]);
 const patch=(v:Partial<EvaluationSettings>)=>setDraft(old=>({...old,...v}));
 const save=async()=>{setBusy(true);setMessage('');try{const valid=normalizeEvaluationSettings(draft);await onSave(valid);saveEvaluationPreferences(valid);setMessage('Pengaturan Evaluasi AI tersimpan. Kuis yang sudah dibuat tetap memakai snapshot sebelumnya.');}catch(e){setMessage(safeError(e));}finally{setBusy(false);}};
 const test=async()=>{setBusy(true);setMessage('');try{
  const q={id:'probe',type:'short_answer' as const,question:'Berapa hasil dua ditambah dua?',referenceAnswer:'4',acceptedAnswers:['4'],requiredConcepts:['Hasil penjumlahan 2+2 adalah 4'],maxLength:500,caseSensitive:false,allowPartial:false,explanation:'2 + 2 = 4.',groundingSources:[]};
  const quiz:Quiz={id:'probe-quiz',schemaVersion:2,title:'Uji evaluator',topic:'Penjumlahan',summary:'Uji evaluator',difficulty:'easy',timeLimitMinutes:0,createdAt:new Date().toISOString(),questions:[q],provider:draft.provider,model:draft.model};
  const submission:QuizSubmission={quizId:quiz.id,attemptId:crypto.randomUUID(),userAnswers:{probe:{type:'short_answer',text:'Empat'}},bookmarkedQuestions:[],timeTakenSeconds:0,completedAt:new Date().toISOString()};
  const response=await fetchApi('/api/evaluate-quiz',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quiz,submission,settings:{...normalizeEvaluationSettings(draft),enabled:true,followGenerator:false,shortAnswerMode:'ai'},targetQuestionIds:['probe']}),signal:AbortSignal.timeout(120000)});const data=await response.json();const e=data.evaluations?.probe;if(!response.ok||!data.success||e?.status!=='graded')throw new Error(data.error??e?.feedback??'Evaluator belum berhasil dinilai.');setMessage(`Uji evaluator berhasil: ${e.model}, nilai ${e.earnedPoints}/${e.maxPoints}. Uji ini menggunakan kuota.`);
 }catch(e){setMessage(safeError(e));}finally{setBusy(false);}};
 const modelField=(label:string,provider:AIProvider,key:'model'|'fallbackModel'|'fallbackProviderModel')=><div><label htmlFor={'eval-'+key} className="field-label">{label}</label><input id={'eval-'+key} className="field-input" list={'eval-list-'+key} value={draft[key]} onChange={e=>patch({[key]:e.target.value})} maxLength={120}/><datalist id={'eval-list-'+key}>{AI_MODELS.filter(m=>m.provider===provider).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</datalist></div>;
 return <section className="evaluation-settings" aria-busy={busy}><div className="connection-section-heading"><div><h3>Evaluasi AI</h3><p>Nilai isian singkat dan esai berdasarkan standar jawaban dan rubrik. Model penilai dapat berbeda dari model pembuat soal.</p></div></div><fieldset disabled={busy}>
 <label className="key-checkbox"><input type="checkbox" checked={draft.enabled} onChange={e=>patch({enabled:e.target.checked})}/>Aktifkan evaluasi AI setelah kuis dikumpulkan</label>
 <label className="key-checkbox"><input type="checkbox" checked={draft.followGenerator} onChange={e=>patch({followGenerator:e.target.checked})}/>Ikuti model pembuat soal</label>
 <p className="field-help">Untuk uji evaluator dan model cadangan, gunakan pilihan penyedia/model di bawah.</p>
 <label className="field-label" htmlFor="eval-provider">Penyedia evaluator</label><select id="eval-provider" className="field-input" value={draft.provider} onChange={e=>{const provider=e.target.value as AIProvider;patch({provider,model:defaultProviderModel(provider),fallbackModel:defaultProviderModel(provider)});}}><option value="gemini">Google Gemini</option><option value="groq">Groq</option></select>{modelField('Model evaluator',draft.provider,'model')}
 <label className="field-label" htmlFor="eval-short">Penilaian isian singkat</label><select id="eval-short" className="field-input" value={draft.shortAnswerMode} onChange={e=>patch({shortAnswerMode:e.target.value as 'hybrid'|'ai'})}><option value="hybrid">Alias sah secara lokal, jawaban lainnya dinilai AI</option><option value="ai">Semua jawaban nonkosong dinilai AI</option></select>
 <label className="key-checkbox"><input type="checkbox" checked={draft.reviewFlagged} onChange={e=>patch({reviewFlagged:e.target.checked})}/>Tinjau hasil yang ambigu atau bermasalah sebelum nilai final</label>
 <details className="connection-advanced"><summary>Cadangan evaluator & batas penggunaan</summary><label className="key-checkbox"><input type="checkbox" checked={draft.allowKeyFallback} onChange={e=>patch({allowKeyFallback:e.target.checked})}/>Gunakan key cadangan dari penyedia yang sama</label><label className="key-checkbox"><input type="checkbox" checked={draft.allowModelFallback} onChange={e=>patch({allowModelFallback:e.target.checked})}/>Izinkan model cadangan evaluator</label>{draft.allowModelFallback&&modelField('Model cadangan',draft.provider,'fallbackModel')}<label className="key-checkbox"><input type="checkbox" checked={draft.allowProviderFallback} onChange={e=>patch({allowProviderFallback:e.target.checked})}/>Izinkan penyedia cadangan menerima pertanyaan, rubrik, dan jawaban Anda</label>{draft.allowProviderFallback&&<><label className="field-label" htmlFor="eval-backup-provider">Penyedia cadangan</label><select id="eval-backup-provider" className="field-input" value={draft.fallbackProvider} onChange={e=>{const p=e.target.value as AIProvider;patch({fallbackProvider:p,fallbackProviderModel:defaultProviderModel(p)});}}><option value="gemini">Gemini</option><option value="groq">Groq</option></select>{modelField('Model penyedia cadangan',draft.fallbackProvider,'fallbackProviderModel')}</>}<p className="field-help">Maksimal 3 percobaan per jawaban, termasuk cadangan. Tidak ada pencarian web saat penilaian. Isian: batas 60 detik; esai: 120 detik per batch. Jawaban tersimpan di perangkat; dikirim ke penyedia hanya saat evaluasi.</p></details>
 <div className="key-actions"><button type="button" className="connection-primary" onClick={()=>void save()}>Simpan pengaturan evaluator</button><button type="button" className="topic-chip" onClick={()=>void test()}>Uji evaluator · menggunakan kuota</button></div></fieldset><p role="status" className="field-help">{message}</p></section>;
}
