import React from 'react';
import { QUESTION_TYPES,type QuestionType,type EvaluationSettings } from '../types/quiz.js';
import { questionLabels } from '../questionState.js';
export interface Composition {mode:'single'|'mixed';type:QuestionType;distribution:Partial<Record<QuestionType,number>>;points:Partial<Record<QuestionType,number>>;partialCredit:boolean;times?:Partial<Record<QuestionType,number>>}
export const defaultComposition:Composition={mode:'single',type:'single_choice',distribution:{single_choice:5,multiple_select:5},points:{},partialCredit:false};
export function QuestionComposition({value:v,onChange,count,evaluator,onOpen,sequential=false}:{sequential?:boolean;value:Composition;onChange:(v:Composition)=>void;count:number;evaluator:EvaluationSettings;onOpen?:()=>void}){
 const patch=(p:Partial<Composition>)=>onChange({...v,...p}),active=QUESTION_TYPES.filter(t=>v.mode==='single'?t===v.type:(v.distribution[t]??0)>0),open=active.some(t=>t==='short_answer'||t==='essay');
 return <section className="surface section-pad question-composition"><h2>Tipe soal</h2><div className="key-actions">{(['single','mixed'] as const).map(mode=><label key={mode} className="key-checkbox"><input type="radio" name="composition" checked={v.mode===mode} onChange={()=>patch({mode})}/>{mode==='single'?'Satu tipe':'Campuran'}</label>)}</div>
 {v.mode==='single'?<><label htmlFor="question-type" className="field-label">Pilih tipe soal</label><select id="question-type" className="field-input" value={v.type} onChange={e=>patch({type:e.target.value as QuestionType})}>{QUESTION_TYPES.map(t=><option key={t} value={t}>{questionLabels[t]}</option>)}</select></>:<><div className="type-distribution">{QUESTION_TYPES.map(t=><div key={t}><label className="key-checkbox"><input type="checkbox" checked={(v.distribution[t]??0)>0} onChange={e=>patch({distribution:{...v.distribution,[t]:e.target.checked?1:0}})}/>{questionLabels[t]}</label><input aria-label={'Jumlah '+questionLabels[t]} className="field-input" type="number" min={0} max={100} value={v.distribution[t]??0} onChange={e=>patch({distribution:{...v.distribution,[t]:Number(e.target.value)}})}/></div>)}</div><p className="field-help" role="status">Total {Object.values(v.distribution).reduce((n,i)=>n+(i??0),0)} soal (maksimal 100).</p><button type="button" className="topic-chip" disabled={!active.length} onClick={()=>{const total=Math.min(100,Math.max(active.length,count||10));patch({distribution:Object.fromEntries(active.map((t,i)=>[t,Math.floor(total/active.length)+(i<total%active.length?1:0)]))});}}>Bagi merata</button></>}
 <p className="field-help">Pilihan ganda biasa dan kompleks menggunakan 5 opsi A–E. Pilihan ganda kompleks bisa memiliki beberapa jawaban benar.</p>
 <details className="connection-advanced"><summary>Penilaian & bobot</summary><label className="key-checkbox"><input type="checkbox" checked={v.partialCredit} onChange={e=>patch({partialCredit:e.target.checked})}/>Kredit parsial untuk pilihan ganda kompleks dan mengurutkan</label><p className="field-help">Menjodohkan dinilai per pasangan. Bawaan setiap soal bernilai 1 poin.</p>{active.map(t=><div className="matching-row" key={t}><label htmlFor={'points-'+t}>{questionLabels[t]} · poin per soal</label><input id={'points-'+t} type="number" min={1} max={20} className="field-input" value={v.points[t]??1} onChange={e=>patch({points:{...v.points,[t]:Math.min(20,Math.max(1,Number(e.target.value)||1))}})}/></div>)}</details>
 {sequential&&<details className="connection-advanced"><summary>Waktu per tipe soal</summary><p className="field-help">Kosong mengikuti waktu umum. Nilai 0 memberi waktu tanpa batas untuk tipe tersebut.</p>{active.map(t=><div className="matching-row" key={t}><label htmlFor={'time-'+t}>{questionLabels[t]} · detik</label><input id={'time-'+t} className="field-input" type="number" min={0} max={600} placeholder="Ikuti waktu umum" value={v.times?.[t]??''} onChange={e=>{const times={...v.times};if(e.target.value==='')delete times[t];else times[t]=Math.min(600,Math.max(0,Math.round(Number(e.target.value)||0)));patch({times});}}/></div>)}</details>}
 {open&&<div className="evaluation-summary"><strong>{evaluator.enabled?'Dinilai AI setelah dikumpulkan':'Evaluasi AI nonaktif · evaluasi nanti atau tinjau manual'}</strong><p>{evaluator.followGenerator?'Mengikuti model pembuat soal':evaluator.provider+' · '+evaluator.model}. Jawaban tetap tersimpan jika penilaian gagal.</p><button type="button" className="topic-chip" onClick={onOpen}>Kelola Evaluasi AI</button></div>}</section>;
}
