import React,{useState} from 'react';
import type { QuizResult,QuestionEvaluation } from '../types/quiz.js';
import { Button } from './Button.js';
import { QuestionReview } from './QuestionReview.js';
import { questionLabels,questionType } from '../questionState.js';
import { buildResult } from '../scoring.js';
import { exportJSON } from '../quizStorage.js';
import { modelName } from '../models.js';
import { Trophy,Printer,RotateCcw,Plus } from 'lucide-react';
interface Props {result:QuizResult;onRetake:()=>void;onNewQuiz:()=>void;isEvaluating?:boolean;onEvaluate?:(ids?:string[])=>void;onCancelEvaluation?:()=>void;onOpenConnections?:()=>void;onReview?:(id:string,points:number,reason:string)=>void}
const statusLabel=(e:QuestionEvaluation)=>e.status==='unanswered'?'Belum dijawab':e.status==='needs_review'?'Perlu tinjauan':e.status==='failed'?'Evaluasi gagal':e.status==='cancelled'?'Evaluasi dibatalkan':e.earnedPoints===null?'Menunggu evaluasi':e.earnedPoints===e.maxPoints?'Benar':e.earnedPoints===0?'Salah':'Sebagian benar';
function ReviewControl({id,e,onReview}:{id:string;e:QuestionEvaluation;onReview:NonNullable<Props['onReview']>}){
 const [points,setPoints]=useState(String(e.proposedPoints??e.earnedPoints??'')),[reason,setReason]=useState('');const number=Number(points),valid=points.trim()!==''&&Number.isFinite(number)&&number>=0&&number<=e.maxPoints&&!!reason.trim();
 return <details className="manual-review print:hidden"><summary>Tinjau / sesuaikan nilai</summary><p className="field-help">Latihan pribadi: perubahan Anda disimpan bersama alasan dan nilai sebelumnya.</p><label className="field-label" htmlFor={'manual-'+id}>Poin (0–{e.maxPoints})</label><input id={'manual-'+id} className="field-input" type="number" min={0} max={e.maxPoints} step="0.01" value={points} onChange={v=>setPoints(v.target.value)}/><label className="field-label" htmlFor={'reason-'+id}>Alasan penetapan nilai</label><textarea id={'reason-'+id} className="field-input" value={reason} maxLength={1000} onChange={v=>setReason(v.target.value)} rows={2}/><button type="button" className="topic-chip" disabled={!valid} onClick={()=>onReview(id,number,reason.trim())}>Simpan nilai manual</button>{e.status==='needs_review'&&e.proposedPoints!==undefined&&<button type="button" className="topic-chip" onClick={()=>onReview(id,e.proposedPoints!,'Menerima nilai usulan AI setelah meninjau rubrik.')}>Terima usulan AI: {e.proposedPoints}/{e.maxPoints}</button>}</details>;
}
export const QuizResults:React.FC<Props>=({result,onRetake,onNewQuiz,isEvaluating=false,onEvaluate,onCancelEvaluation,onOpenConnections,onReview})=>{
 const [filter,setFilter]=useState('all'),data=result.evaluations?result:buildResult(result.quiz,result.submission),evaluations=data.evaluations!,score=result.finalScore===undefined?result.score:result.finalScore;
 const filters=['all','correct','partial','incorrect','unanswered','pending'],labels=['Semua','Benar','Sebagian benar','Salah','Belum dijawab','Belum final'];
 const matches=(e:QuestionEvaluation)=>filter==='all'||filter==='pending'&&e.earnedPoints===null||filter==='unanswered'&&e.status==='unanswered'||filter==='correct'&&e.status==='graded'&&e.earnedPoints===e.maxPoints||filter==='partial'&&e.status==='graded'&&e.earnedPoints!>0&&e.earnedPoints!<e.maxPoints||filter==='incorrect'&&e.status==='graded'&&e.earnedPoints===0;
 return <div className="page-shell results-page"><div className="page-heading"><div className="eyebrow"><Trophy size={15}/> HASIL SESI BELAJAR</div><h1>{score===null?'Jawaban tersimpan. Penilaian belum selesai.':'Setiap latihan membawa kemajuan.'}</h1><p>{result.quiz.title}</p></div>
 <section className="surface result-overview"><div className="result-intro"><h2>{score===null?'Hasil sementara':'Hasil akhir'}</h2><p>{data.evaluationAnalysis}</p><p className="field-help">{result.quiz.questions.length} soal · {Math.floor(result.submission.timeTakenSeconds/60)}m {result.submission.timeTakenSeconds%60}d · Pembuat soal: {modelName(result.quiz.model)}</p><p className="field-help">{new Date(result.submission.completedAt).toLocaleString('id-ID')}</p></div><div className="score-block"><div className="score-ring" style={{'--score-angle':String((score??data.score)*3.6)+'deg'} as React.CSSProperties}><div><strong>{score??'—'}</strong><span>{score===null?'Belum final':'dari 100'}</span></div></div><p>Poin terkonfirmasi {data.earnedPoints?.toFixed(2)} / {data.totalPoints}</p></div>
 <div className="result-metrics">{[['Benar penuh',data.correctCount],['Sebagian benar',data.partialCount??0],['Salah',data.incorrectCount],['Belum dijawab',data.unansweredCount],['Belum final',data.pendingCount??0]].map(([label,value])=><div key={String(label)} className="result-metric"><div><span>{label}</span><strong>{value}</strong></div></div>)}</div>
 <div className="result-footer print:hidden"><div className="key-actions"><Button label="Cetak" icon={<Printer size={16}/>} variant="ghost" onClick={()=>window.print()}/><button type="button" className="topic-chip" onClick={()=>exportJSON('quizmind-hasil-'+result.quiz.id+'.json',result)}>Ekspor jawaban & hasil</button><Button label="Kerjakan ulang" icon={<RotateCcw size={16}/>} variant="outline" onClick={onRetake}/><Button label="Kuis baru" icon={<Plus size={16}/>} onClick={onNewQuiz}/></div></div></section>
 {(data.pendingCount??0)>0&&<section className="surface section-pad evaluation-progress" aria-live="polite"><h2>{isEvaluating?'Evaluasi AI sedang berjalan':'Lanjutkan penilaian'}</h2><p>{result.quiz.questions.length-(data.pendingCount??0)} dari {result.quiz.questions.length} soal mempunyai nilai final. Jawaban Anda tetap tersimpan.</p><div className="key-actions">{isEvaluating?<button type="button" className="topic-chip" onClick={onCancelEvaluation}>Batalkan evaluasi</button>:<><button type="button" className="connection-primary" onClick={()=>onEvaluate?.()}>Evaluasi yang belum selesai · memakai kuota</button><button type="button" className="topic-chip" onClick={onOpenConnections}>Kelola Evaluasi AI</button></>}</div></section>}
 <section className="review-section"><div className="review-heading"><div><h2>Pembahasan soal</h2><p>Bandingkan jawaban dengan kunci atau rubrik penilaian.</p></div><div className="review-filters print:hidden">{filters.map((f,i)=><button type="button" key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{labels[i]}</button>)}</div></div><div className="space-y-4">{result.quiz.questions.filter(q=>matches(evaluations[q.id])).map(q=>{const e=evaluations[q.id];return <article key={q.id} className="surface review-card"><div className="flex flex-wrap justify-between items-center gap-3 mb-5"><span className="question-counter">SOAL {result.quiz.questions.indexOf(q)+1} · {questionLabels[questionType(q)]}</span><span className={'answer-status '+(e.earnedPoints===e.maxPoints?'correct':e.earnedPoints===null?'empty':'incorrect')}>{statusLabel(e)} · {e.earnedPoints??'—'}/{e.maxPoints} poin</span></div><h3 className="question-title">{q.question}</h3><QuestionReview question={q} answer={result.submission.userAnswers[q.id]} evaluation={e}/>{(q.type==='short_answer'||q.type==='essay')&&!isEvaluating&&<>{onReview&&<ReviewControl id={q.id} e={e} onReview={onReview}/>}<button type="button" className="topic-chip print:hidden" onClick={()=>onEvaluate?.([q.id])}>Nilai ulang soal ini · memakai kuota</button></>}</article>;})}</div></section></div>;
};
