import { build } from 'esbuild';
import { mkdir, writeFile } from 'node:fs/promises';
const result = await build({ entryPoints: ['src/server/geminiService.ts'], bundle: true, write: false, format: 'esm', platform: 'browser', external: ['@google/genai'], minify: false });
await mkdir('supabase/functions/_shared', { recursive: true });
await writeFile('supabase/functions/_shared/quiz-engine.ts', '// @ts-nocheck -- generated by scripts/build-edge.mjs\n' + result.outputFiles[0].text.replace('"@google/genai"', '"npm:@google/genai@2.4.0"'));
const evaluation = await build({ entryPoints: ['src/server/evaluationService.ts'], bundle: true, write: false, format: 'esm', platform: 'browser', external: ['@google/genai'], minify: false });
await writeFile('supabase/functions/_shared/evaluation-engine.ts', '// @ts-nocheck -- generated by scripts/build-edge.mjs\n' + evaluation.outputFiles[0].text.replace('"@google/genai"', '"npm:@google/genai@2.4.0"'));
// A single deployable file for the Supabase dashboard editor.
const edge = await build({ entryPoints: ['supabase/functions/quiz-ai/index.ts'], bundle: true, write: false, format: 'esm', platform: 'browser', external: ['npm:*'], minify: true });
await mkdir('build', { recursive: true });
await writeFile('build/quiz-ai.ts', '// @ts-nocheck\n' + edge.outputFiles[0].text);
const relay = await build({ entryPoints: ['supabase/functions/parallel-search/index.ts'], bundle: true, write: false, format: 'esm', platform: 'browser', minify: true });
await writeFile('build/parallel-search.ts', '// @ts-nocheck\n' + relay.outputFiles[0].text);
console.log('Supabase Edge source ready.');
